# Generated by Django 5.2.6 on 2026-01-31 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Dentist', 'Dentist'), ('Construction', 'Construction'), ('Clinic', 'Clinic'), ('Other', 'Other')], max_length=50)),
                ('other_category', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('meeting_booked', 'Meeting Booked'), ('deal_won', 'Deal Won'), ('deal_lost', 'Deal Lost')], default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_sales_closer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
