# Generated by Django 5.2.6 on 2026-02-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meeting_details',
            field=models.TextField(blank=True, help_text='Optional details/time for meetings', null=True),
        ),
    ]
