# Generated by Django 5.2.6 on 2025-12-03 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('starter_4k', 'Starter 4k'), ('starter_5k', 'Starter 5k'), ('regular_7k', 'Regular 7k'), ('regular_8k', 'Regular 8k'), ('professional_13k', 'Professional 13k'), ('professional_15k', 'Professional 15k')], max_length=50)),
                ('website_type', models.CharField(choices=[('landing', 'Landing Page'), ('business', 'Business Website'), ('portfolio', 'Portfolio'), ('service', 'Service Website'), ('ecom-lite', 'E-commerce Lite'), ('custom', 'Custom')], max_length=50)),
                ('pages_required', models.TextField(default='[]', help_text='JSON list of required pages')),
                ('business_description', models.TextField()),
                ('services_list', models.TextField(default='[]', help_text='JSON list of services')),
                ('contact_info_phone', models.CharField(max_length=20)),
                ('contact_info_email', models.EmailField(max_length=254)),
                ('contact_info_address', models.TextField()),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('social_instagram', models.URLField(blank=True, null=True)),
                ('social_facebook', models.URLField(blank=True, null=True)),
                ('social_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('logo_drive_link', models.URLField(blank=True, null=True)),
                ('photos_drive_link', models.URLField(blank=True, null=True)),
                ('design_style', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_websites', models.TextField(default='[]', help_text='JSON list of reference websites')),
                ('has_domain', models.BooleanField(default=False)),
                ('has_hosting', models.BooleanField(default=False)),
                ('needs_domain_assistance', models.BooleanField(default=False)),
                ('needs_hosting_assistance', models.BooleanField(default=False)),
                ('needs_maintenance_plan', models.BooleanField(default=False)),
                ('deadline', models.DateField()),
                ('payment_status', models.CharField(choices=[('not_paid', 'Not Paid'), ('paid_advance', 'Paid Advance'), ('paid_full', 'Paid Full')], default='not_paid', max_length=20)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('referral_used', models.BooleanField(default=False)),
                ('referrer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('payment_done', 'Payment Done')], default='new', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_assigned', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('developer_mock_link', models.URLField(blank=True, null=True)),
                ('final_delivery_link', models.URLField(blank=True, null=True)),
                ('developer_notes', models.TextField(blank=True, null=True)),
                ('admin_payment_released', models.BooleanField(default=False)),
                ('fetcher_commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('developer_payout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agency_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Developer assigned to this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client')),
                ('created_by', models.ForeignKey(help_text='Fetcher who submitted this project', on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
