# Generated by Django 5.2.6 on 2026-01-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('professional_10k', 'Professional 10k'), ('professional_15k', 'Professional 15k'), ('professional_25k', 'Professional 25k'), ('professional_40k', 'Professional 40k'), ('custom', 'Custom')], max_length=50),
        ),
    ]
