# Generated by Django 5.2.6 on 2026-01-31 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '__first__'),
        ('projects', '0002_alter_project_project_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_team',
            field=models.ManyToManyField(blank=True, related_name='team_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='current_stage',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('design', 'Design'), ('landing_dev', 'Landing Page Development'), ('client_approval_landing', 'Client Approval (Landing)'), ('full_dev', 'Full Website Development'), ('client_approval_final', 'Client Approval (Final)'), ('deployment', 'Deployment'), ('seo_gbp_ongoing', 'SEO + GBP Ongoing'), ('completed', 'Completed')], default='assigned', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='project',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_40_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_60_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
