# Generated by Django 5.2.6 on 2026-01-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_assigned_payments'),
        ('projects', '0004_alter_project_options_projectupdate'),
    ]

    operations = [
    ]
