# Generated by Django 5.2.6 on 2026-02-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_designer_payout_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_stage',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('design', 'Design'), ('landing_dev', 'Landing Page Development'), ('client_approval_landing', 'Client Approval (Landing)'), ('full_dev', 'Full Website Development'), ('client_approval_final', 'Client Approval (Final)'), ('deployment', 'Deployment'), ('seo_gbp_ongoing', 'SEO + GBP Ongoing'), ('completed', 'Completed')], default='design', max_length=50),
        ),
    ]
