# Generated by Django 5.2.6 on 2026-02-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
